### ISSUE TITLE
Add properties type checking for writing a new value

### ISSUE THREAD

**Issue by Lisennk** [SerafimArts/Properties#1]
I think i can do it.

You need this:

```
$object->some = 1; // lets make it integer
$object->some = "string"; // error: 'some' can be integer only? 
```

or what?

**Comment by SerafimArts** [comment]
@Lisennk https://github.com/SerafimArts/Properties#roadmap ;) Как раз то, что тебе надо. Но мне, признаться, влом это доделывать =(

**Comment by Lisennk** [comment]
так это из этого to-do и есть) я хочу узнать, что конкретно нужно, потому что как-то расплывчато написано. Хочу сделать, ИМХО, очень крутая штука.

**Comment by SerafimArts** [comment]
@Lisennk идея заключается в том, что у тебя есть поля и ты добавляешь для них автокомплит с помощью аннотаций для IDE и код уже следует поведению, которое описано в [доках документатора](https://phpdoc.org/docs/latest/references/phpdoc/tags/property-read.html) и частично [в PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md)

Если ты указал, что поле доступно только для чтения - IDE будет ругаться во время записи туда, ну и наоборот. Как следствие, следуя логике - типы можно брать из этих деклараций, более того - [это уже есть](https://github.com/SerafimArts/Properties/blob/master/src/Support/Declaration.php#L51-L54)

Осталось проверять это всё дело во время вызовов где-то в этом районе: https://github.com/SerafimArts/Properties/blob/master/src/Setters.php#L39 - в данном случае оно проверяет декларацию и вызывает этот метод: https://github.com/SerafimArts/Properties/blob/master/src/Support/Declaration.php#L67

Проверять надо следующее (помимо проверки на равенство декларации и типа):
1) Соответствие сокращениям: integer == int, boolean == bool, float == double и т.д.
2) Цепочка наследования: Надо проверять на instanceof для объектов и is_subclass_of для классов

**Comment by SerafimArts** [comment]
Плюс проблема в консистентности, как правильно определять тип?

```
/** @property-read string $any */ // <- Тут string
class Some
{ 
    /** @var int */ // <- Тут int
    protected $any;
}
```

Что в данном случае будет верным?

Но если следовать логике - все внешние вызовы (доступ к полю извне класса) будут возвращать `string`, так что думаю именно на это надо и ориентироваться, что и делает typeOf метод в классе декларации поля.
