### ISSUE TITLE
Seems like tests are broken

### ISSUE THREAD

**Issue by Lisennk** [SerafimArts/Properties#6]
Try to pull last version and run phpunit. I get the following output:

```
PHPUnit 5.2.9 by Sebastian Bergmann and contributors.

.....................EE..                                         25 / 25 (100%)

Time: 89 ms, Memory: 8.00Mb

There were 2 errors:

1) Serafim\Properties\Unit\WriteTypeHintsTestCase::testWritePrimitives
TypeError: Value for property Serafim\Properties\Unit\Stub\WritableTypeHints::objectValue must be of the type object, object given

/home/taras/work/github.com/Properties/src/Properties.php:90
/home/taras/work/github.com/Properties/tests/WriteTypeHintsTestCase.php:41

2) Serafim\Properties\Unit\WriteTypeHintsTestCase::testConditionalTypes
TypeError: Value for property Serafim\Properties\Unit\Stub\WritableTypeHints::arrayInstanceOfSelfValue must be of the type WritableTypeHints[], array given

/home/taras/work/github.com/Properties/src/Properties.php:90
/home/taras/work/github.com/Properties/tests/WriteTypeHintsTestCase.php:69

FAILURES!
Tests: 25, Assertions: 63, Errors: 2.
```

:) 
`must be of the type object, object given`

**Comment by Lisennk** [comment]
Travis build also fails.

**Comment by SerafimArts** [comment]
It is **valid** test-case failure, test are not broken.  "Object" type-hint validation are broken and does not supports yet: https://github.com/SerafimArts/Properties/blob/master/src/Support/Declaration.php#L99-L115

This test checks this declaraion: https://github.com/SerafimArts/Properties/blob/master/tests/Stub/WritableTypeHints.php#L24 end runs `$obj->objectValue = new \stdClass();`. This query are valid for `object` type-hint, but throws an exception.

**Comment by SerafimArts** [comment]
P.S. Second line (after method of test) - are information about exception **inside** library. This is not exception info of PhpUnit.

**Comment by Lisennk** [comment]
Ok. Answer VK pls :)
